### USER REGISTER 
POST http://localhost:4000/users-api/users
Content-Type: application/json

{
    "firstName":"sergio",
    "lastName":"ramos",
    "email":"sergio@gmamil.com",
    "password":"sergio@134",
    "profileImageurl":"https://example.com/avatars/user.png"
}

### USER LOGIN

POST http://localhost:4000/common-api/authenticate
Content-Type: application/json

{
    "email":"r@gmail.com",
    "password":"123456789"
}

### READING ARTICLES BY USER(PROTECTED)

GET http://localhost:4000/users-api/articles

### ADDING A COMMENT TO THE ARTICLE

PUT http://localhost:4000/users-api/articles
Content-Type: application/json

{ "user":"69ae86f658895e962a185edc",
   "articleId":"69ae8339db61f7722e961ef6",
  "comment": "bad article!"
}

### READING ALL THE COMMENTS OF AN ARTICLE  
GET http://localhost:4000/users-api/comments/69ae8e31631ddca3064aba36



### AUTHOR REGISTER
POST http://localhost:4000/author-api/users
Content-Type: application/json

{
    "firstName":"ravi",
    "lastName":"kumar",
    "email":"ravi@gmail.com",
    "password":"123456789",
    "profileImageurl":"https://example.com/avatars/author.png"
}


### AUTHOR LOGIN

POST http://localhost:4000/common-api/authenticate
Content-Type: application/json

{
    "email":"ravi@gmail.com",
    "password":"123456789",
    "role":"AUTHOR"
}


### Create Article (AUTHOR)

POST http://localhost:4000/author-api/articles
Content-Type: application/json

{
  "author":"69ae8b1435d1aa693da5eded",
  "title":"Java Script",
  "category":"Programming",
  "content":"JS is an object oriented language"
}


### Read All Articles

GET http://localhost:4000/author-api/articles/69ae8b1435d1aa693da5eded


### Edit article (AUTHOR)
PUT http://localhost:4000/author-api/articles
Content-Type: application/json

{
  "author":"6989f8d6b449d9fee9e97b66",
  "articleId":"698a1179b79362aedb398f9b",
  "title":"Python",
  "category":"programming",
  "content":"Python is a programming language"
}

### DELETE the article

PATCH http://localhost:4000/author-api/delete-article/69ae8e31631ddca3064aba36
 

###Logout Route
GET http://localhost:4000/common-api/logout



###Checking invalid path
GET http://localhost:4000/test


###changing password
PUT http://localhost:4000/common-api/change-password
Content-Type: application/json

{
    "email":"raki@gmamil.com",
    "password":"abcdefgh",
    "newPassword":"12345678"
}

###READ ARTICLES BY ADMIN
GET http://localhost:4000/admin-api/articles

###BLOCKING USERS BY USERID
PUT http://localhost:4000/admin-api/block-user/6989f7d3bbffee56863dfd73

###UNBLOCKING USERS BY USERID
PUT http://localhost:4000/admin-api/unblock-user/6989f7d3bbffee56863dfd73

### CREATE ADMIN (requires ADMIN_SECRET set in backend .env)
POST http://localhost:4000/common-api/create-admin
Content-Type: application/json

{
  "firstName": "super",
  "lastName": "admin",
  "email": "admin@blogapp.com",
  "password": "Admin@12345",
  "profileImageUrl": "https://example.com/avatars/admin.png",
  "adminSecret": "admin123"
}

### ADMIN LOGIN
POST http://localhost:4000/common-api/authenticate
Content-Type: application/json

{
  "email": "admin@blogapp.com",
  "password": "Admin@12345"
}
